### ISSUE TITLE
Error:Expected type Upload; Could not get uploaded file.

### ISSUE THREAD

**Issue by carlosloureda** [dre1080/wp-graphql-upload#1]
HI!

Sorry for opening an issue, didn't know the best way to contact!

I am new to the wordress world and wpgraphql and was trying to use this package but seems I don't manage to make it work, hopefully you can help me understand it.

- I am using **nextjs** and **apollo**. 

This is the error I get: **"Variable \"$file\" got invalid value []; Expected type Upload; Could not get uploaded file, be sure to conform to GraphQL multipart request specification. Instead got: []**

I am just getting the file from the input type="file" and sending it on the request (also tried to create a formData with it but no success).

- Just the file (image is e.taget.values[0])
```
 const onFileUpload = () => {
    uploadMediaItem({
      variables: {
        file: image
      }
    })
  };
 ```
 
 - With formData:
 
 ```
 const onFileUpload = () => {
    const formData = new FormData();
    formData.append(
      "myFile",
      image,
      image.name
    );
 
    uploadMediaItem({
      variables: {
        file: formData
      }
    })
  };

```
  
And the query on my client side:

```
const UPLOAD = gql`
  mutation UploadWpGraphql(
    $file: Upload!,
  ) {
    upload(input:{
      file: $file
    }){
      text
    }
  }
```

Thanks!

**Comment by dre1080** [comment]
This seems more of an issue on the javascript side of things. This plugin only registers the `Upload` scalar type & processes it for your server.

Are you sure you're using [Apollo Upload Client](https://github.com/jaydenseric/apollo-upload-client) as well to upload files correctly on the javascript side?
