### ISSUE TITLE
Release WPGraphQL Upload to packagist

### ISSUE THREAD

**Issue by justlevine** [dre1080/wp-graphql-upload#12]
Considering the reliance on dependency management in the headless world, it would would be really helpful to be able to run `composer require dre1080/wp-graphql-upload` in order to install the plugin.

Currently you either need to:
1. manually download and install the zip file on the WP backend,
2. add configure this repo in `composer.repositories[]`, or
3. Pipe the release url to `wp cli`.

None of these are particularly friendly, and only the second one provides users with version update notifications.

Nowadays, adding a repo to packagist is easy and automatic with an [official Github Hook](https://packagist.org/about#:~:text=to%20update%20packages%3F-,GitHub%20Hook,-Enabling%20the%20Packagist), so once set up no additional maintainer work is required.

**Comment by dre1080** [comment]
No worries. This is already available [here](https://packagist.org/packages/dre1080/wp-graphql-upload).

**Comment by justlevine** [comment]
Not sure how I missed that all this time 😂 thanks!
