### ISSUE TITLE
Cant move uploaded files. 

### ISSUE THREAD

**Issue by justlevine** [dre1080/wp-graphql-upload#2]
I cant move the uploaded files once they are on the server. The file appears in `\tmp`, and the destination file has the correct permissions. Any ideas?

E.g.
```php
public function mutate_and_get_payload() : callable {
  return function( $input, AppContext $context, ResolveInfo $info ) : array {
    $file = get_file_upload_value( $input); // returns if FileUpload value was passed to the mutation, or throws execption.
    
    $target = get_my_target_path(); 
    
    if ( ! is_writable( $dirname( $target['path'] ) ) {
      throw new UserError( 'Failed permission message' );
    }
    
    if ( ! file_exists( $file['tmp_name'] ) {
      throw new UserError( 'File doesnt exist on server message' );
    }
    
    // This execption gets thrown!!!!!
    if( ! move_file_upload( $file['tmp_name'], $target['path'] ) {
      /// @todo delete tmp upload.
      throw new UserError( ' Could not move file ');
    }
    
    return $target['url'];
  
  }

}

**Comment by dre1080** [comment]
This is out of the scope of this plugin as this is a server specific error. 

What is the error being thrown? Have you checked php logs?

Have you tried using the wordpress provided methods for moving files like [`wp_handle_sideload`](https://developer.wordpress.org/reference/functions/wp_handle_sideload/) or [`wp_handle_upload`](https://developer.wordpress.org/reference/functions/wp_handle_upload/)?

**Comment by justlevine** [comment]
`wp_handle_sideload` works fine. `wp_handle_upload` doesn't, as it uses `move_uploaded_file`.

Further testing shows that `is_uploaded_file` fails. Whish is why I assume this is within the scope of the plugin. Shouldnt the file be recognized as being uploaded via HTTP POST  ?

**Comment by dre1080** [comment]
Yes, it is recognized as uploaded via HTTP POST. All the plugin does is get the reference of your file from the `$_FILES` array and put it in your mutation input field. 

I cannot replicate this issue as both `wp_handle_upload` and `move_uploaded_file` are working for me. 

This must be a server or permissions error.
