### ISSUE TITLE
This file type is not permitted for security reasons

### ISSUE THREAD

**Issue by koraysels** [dre1080/wp-graphql-upload#4]
hi, every time i try to upload a simple jpg or png image I get the following error message:

error 500 `This file type is not permitted for security reasons`

**Comment by dre1080** [comment]
Hi, sorry, but, this is out of the scope for this plugin. This plugin **does not** change any server settings. It just maps files from $_FILES array into your graphql input. 

Please only post issues related to this plugin specifically. 

See #1 and #2
