### ISSUE TITLE
Trouble getting the basic example to work

### ISSUE THREAD

**Issue by ghost** [dre1080/wp-graphql-upload#7]
Hi there. I followed the readme and I am getting an internal server error on upload. Do you have a working example in React of how to send a file to the mutation?

**Comment by dre1080** [comment]
You are supposed to use apollo upload client as well. There are client examples available [here](https://github.com/jaydenseric/apollo-upload-client) and a server example available [in the README](https://github.com/dre1080/wp-graphql-upload#usage). This plugin is meant to be used on a graphql server to enable the client plugin to work.

What is the server error?

**Comment by leefroese** [comment]
I would also love to see some more detailed examples for working with the client using Nuxt / Vue. Struggling to get this to work so far.

**Comment by dre1080** [comment]
@leefroese Sorry, but, that is beyond the scope of this plugin. 

This plugin is only to enable your server to be able to handle `Upload` scalar types and enable you to receive the file on your server.

For client examples and implementations see [apollo-upload-client](https://github.com/jaydenseric/apollo-upload-client).
 
This is only a server implementation.
