### ISSUE TITLE
Wpgraphql upload file

### ISSUE THREAD

**Issue by Nickyle** [dre1080/wp-graphql-upload#8]
Hello,
Nice to meet you!
I want to upload file from computer to website via by graphql. Can you show me how to use your plugin?

**Comment by dre1080** [comment]
Hello, please check out the README. This plugin is only to enable your server to be able to handle `Upload` scalar types and enable you to receive the file on your server.

You are to meant use [this apollo plugin here](https://github.com/jaydenseric/apollo-upload-client) to upload from your forms.

There are client examples available [here](https://github.com/jaydenseric/apollo-upload-client) and a server example available [in the README](https://github.com/dre1080/wp-graphql-upload#usage).
