### ISSUE TITLE
How does multiple upload work?

### ISSUE THREAD

**Issue by mertosman** [dre1080/wp-graphql-upload#9]
Hello, 

Thank you very much for your plugin. Saved lives in file uploads.

But I have a problem, I cannot upload multiple files.

First, I made my species definition. There is no problem in single installation, but the field named "attachments" must be multiple.

I am sharing the screenshots below, I would be very happy if you could help.

![CleanShot 2022-08-17 at 14 49 56@2x](https://user-images.githubusercontent.com/9094446/185111790-83523947-7b03-4faa-8b54-c330f2ebf489.png)

![CleanShot 2022-08-17 at 14 50 47@2x](https://user-images.githubusercontent.com/9094446/185111754-869b7900-c410-41e0-9918-7f17a8513e4d.png)

Thank you.

**Comment by dre1080** [comment]
Hi! Thanks for the kind words!

Try this:

```php
$input_fields['attachments'] = [
  'type' => ['list_of' => ['non_null' => 'Upload']], // or ['list_of' =>'Upload']
  'description' => __('Comment attachments', 'dr'),
];
```

**Comment by mertosman** [comment]
Thank you. It's done.
